tasks:
# prep steps for ICP 
  - init: |
      sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"
      export PATH=$PATH:/home/gitpod/bin
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      cargo install --git https://github.com/dfinity/experimental-minting-tool
    command: |
      cd /workspace/nft-links/blockchain/icp
      dfx start --background --clean
      dfx deploy --no-wallet --argument \
      "(record {
          name = \"Numbers One Through Fifty\";
          symbol = \"NOTF\";
          logo = opt record {
              data = \"$(base64 -i ./logo.png)\";
              logo_type = \"image/png\";
          };
          custodians = opt vec { principal \"$(dfx identity get-principal)\" };
      })"
      minting-tool local "$(dfx canister id dip721_nft_container)" --owner "$(dfx identity get-principal)" --file ./logo.png --sha2-auto

# inits dip721
# mints NFT
  
  



