-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.reward_program
    ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Let owners of reward_program see and modify them"
    ON public.reward_program
    AS PERMISSIVE
    FOR ALL
    TO public
    USING ((auth.uid() = owner));

ALTER TABLE IF EXISTS public.reward_groups
    ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow only admins to modify reward_programs"
    ON public.reward_groups
    AS PERMISSIVE
    FOR ALL
    TO public
    USING ((EXISTS ( SELECT 1
   FROM reward_program g
  WHERE ((g.id = reward_groups.reward_program) AND (g.owner = auth.uid())))));

ALTER TABLE IF EXISTS public.reward_nft
    ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Lets owners of reward_program modify attached nfts"
    ON public.reward_nft
    AS PERMISSIVE
    FOR ALL
    TO public
    USING ((EXISTS ( SELECT 1
   FROM reward_program g
  WHERE ((g.id = reward_nft.reward_program) AND (g.owner = auth.uid())))));
