-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.graph_projects
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    user_id uuid NOT NULL,
    repository character varying COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    name character varying COLLATE pg_catalog."default",
    chain character varying COLLATE pg_catalog."default",
    CONSTRAINT graph_projects_pkey PRIMARY KEY (id),
    CONSTRAINT graph_projects_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.graph_projects
    OWNER to postgres;

ALTER TABLE IF EXISTS public.graph_projects
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.graph_projects TO anon;

GRANT ALL ON TABLE public.graph_projects TO authenticated;

GRANT ALL ON TABLE public.graph_projects TO postgres;

GRANT ALL ON TABLE public.graph_projects TO service_role;

COMMENT ON TABLE public.graph_projects
    IS 'graph projects created by user ';
CREATE POLICY "Enable delete for users based on user_id"
    ON public.graph_projects
    AS PERMISSIVE
    FOR DELETE
    TO public
    USING ((auth.uid() = user_id));
CREATE POLICY "Enable insert for users based on user_id "
    ON public.graph_projects
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Enable select for users based on user_id"
    ON public.graph_projects
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.uid() = user_id));
CREATE POLICY "Enable update for users based on user_id"
    ON public.graph_projects
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING ((auth.uid() = user_id));
