name: Migration for Prod DB

on:
  push:
    branches:
      - "**"
      - "!main"
    tags-ignore:
      - "*"

jobs:
  migration:
    runs-on: ubuntu-latest
    # needs: changes
    # if: ${{ needs.changes.outputs.migrations == 'true' }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Install Supabase CLI
        run: brew install supabase/tap/supabase

      - name: Set Remote DB
        shell: bash
        env:
          SUPABASE_PORT: 6543
        run: |
          supabase db remote set postgresql://postgres:${{ secrets.SUPABASE_PASSWORD }}@db.${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co:${{ env.SUPABASE_PORT }}/postgres
          supabase db push --dry-runsupabase db push --dry-run
      - name: Push Migrations dry run
        run: supabase db push --dry-run
# changes:
#   runs-on: ubuntu-latest
#   outputs:
#     migrations: ${{ steps.filter.outputs.migrations }}
#   steps:
#     - uses: dorny/paths-filter@v2
#       id: filter
#       with:
#         filters: |
#           migrations:
#             - 'supabase/migrations/**'
